networks:
  monitoring:

services:
  influxdb:
    image: influxdb:2.6-alpine
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - monitoring
  telegraf:
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - 3000:3000
    networks:
      - monitoring

volumes:
  influxdbv2:
