networks:
  monitoring:

services:
  influxdb:
    image: influxdb:2.6-alpine
    env_file:
      - ./influxdb/influxv2.env
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    networks:
      - monitoring
  telegraf:
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - ./influxdb/influxv2.env
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - 3000:3000
    networks:
      - monitoring
  mongo:
    image: mongo:4.2
    restart: always
    env_file:
      - ./mongo/mongo.env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongo/mongo_express.env

volumes:
  influxdbv2:
