name: CI
on:
  pull_request:
  push:
    branches:
      - master
env:
  PYTHON_VERSION: "3.11.2"
jobs:
  static-analysis:
    environment: operations
    name: Voyager I | Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install PipEnv
        run: python -m pip install pipenv
      - name: Create pipenv environment
        run: pipenv install --dev
      - name: Run pre-commit
        run: pipenv run pre-commit run --to-ref HEAD --from-ref origin/master
  unit:
    environment: operations
    name: Voyager II | Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install PipEnv
        run: python -m pip install pipenv
      - name: Create pipenv environment
        run: pipenv install --dev
      - name: Run Logs unit tests
        run: pipenv run logs-test
      - name: Run Metadata unit tests
        run: pipenv run metadata-test
